const data = [
  {
    _id: { oid: "537f3aaac769230000be7e5f" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/51i1Xy1BxHL._SL75_.jpg",
        width: "75",
        height: "70",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/51i1Xy1BxHL._SL160_.jpg",
        width: "160",
        height: "149",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/51i1Xy1BxHL.jpg",
        width: "500",
        height: "467",
      },
    },
    description: [
      "Assassin'S Creed Ultimate Collection 1 & 2 Jc (Win Xpvistawin 7)",
    ],
    metadata: [
      { key: "binding", value: "Video Game" },
      { key: "brand", value: "Encore Software" },
      {
        key: "catalognumberlist",
        value: { CatalogNumberListElement: ["4747836", "8087601"] },
      },
      { key: "ean", value: "0705381267324" },
      { key: "esrbagerating", value: "Mature" },
      {
        key: "feature",
        value: [
          "Sequel to the original Assassin's Creed continues the storyline as you fight to uncover a conspiracy bigger than you could imagine",
          "Utilize an arsenal of weapons",
          "You are an Assassin, a warrior shrouded in secrecy and feared for your ruthlessness.",
        ],
      },
      { key: "format", value: "CD-ROM" },
      { key: "genre", value: "Fighting Action Games" },
      { key: "hardwareplatform", value: "Pc" },
      { key: "label", value: "Encore Software" },
      { key: "manufacturer", value: "Encore Software" },
      { key: "model", value: "26732" },
      { key: "mpn", value: "26732" },
      { key: "numberofitems", value: 1 },
      { key: "operatingsystem", value: "Windows 2000" },
      { key: "packagequantity", value: "1" },
      { key: "partnumber", value: "26732" },
      {
        key: "platform",
        value: ["Windows 7", "Windows Vista", "Windows 2000", "Windows XP"],
      },
      { key: "productgroup", value: "Video Games" },
      { key: "producttypename", value: "SOFTWARE_GAMES" },
      { key: "publisher", value: "Encore Software" },
      { key: "releasedate", value: { $date: "2011-09-01T00:00:00.000+0200" } },
      { key: "studio", value: "Encore Software" },
      { key: "title", value: "Assassin's Creed I & II" },
      { key: "upc", value: "705381267324" },
      { key: "upclist", value: { UPCListElement: ["705381267324"] } },
    ],
    binding: "Video Game",
    brand: "Encore Software",
    catalognumberlist: { CatalogNumberListElement: ["4747836", "8087601"] },
    ean: "0705381267324",
    esrbagerating: "Mature",
    feature: [
      "Sequel to the original Assassin's Creed continues the storyline as you fight to uncover a conspiracy bigger than you could imagine",
      "Utilize an arsenal of weapons",
      "You are an Assassin, a warrior shrouded in secrecy and feared for your ruthlessness.",
    ],
    format: "CD-ROM",
    genre: "Fighting Action Games",
    hardwareplatform: "Pc",
    label: "Encore Software",
    price: 999,
    currency: "USD",
    manufacturer: "Encore Software",
    model: "26732",
    mpn: "26732",
    numberofitems: 1,
    operatingsystem: "Windows 2000",
    packagequantity: "1",
    partnumber: "26732",
    platform: ["Windows 7", "Windows Vista", "Windows 2000", "Windows XP"],
    productgroup: "Video Games",
    producttypename: "SOFTWARE_GAMES",
    publisher: "Encore Software",
    releasedate: { $date: "2011-09-01T00:00:00.000+0200" },
    studio: "Encore Software",
    title: "Assassin's Creed I & II",
    upc: "705381267324",
    upclist: { UPCListElement: ["705381267324"] },
    category: "/games/pc",
    salesrank: 1187,
  },
  {
    _id: { oid: "537f3aaac769230000be7e60" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/41kXCp%2BUyeL._SL75_.jpg",
        width: "53",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/41kXCp%2BUyeL._SL160_.jpg",
        width: "113",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/41kXCp%2BUyeL.jpg",
        width: "353",
        height: "500",
      },
    },
    description: [
      "This world was saved twenty years prior by a handful of unnamed heroes in Diablo II. Warriors that survived the onslaught of the armies of the Burning Hells have gone mad from their ordeals and it is up to a new generation of heroes to face the forces of evil threatening the world of Sanctuary. Players will have the opportunity to explore familiar settings such as Tristram.<br /><br />This game will work on PC or Mac with the one disc that comes in the box. Internet connection is required.",
    ],
    metadata: [
      { key: "binding", value: "Computer Game" },
      { key: "brand", value: "Blizzard Entertainment" },
      {
        key: "catalognumberlist",
        value: { CatalogNumberListElement: ["020626728515", "72851"] },
      },
      { key: "department", value: "mens" },
      { key: "ean", value: "0020626728515" },
      { key: "edition", value: "Standard" },
      { key: "esrbagerating", value: "Mature" },
      {
        key: "feature",
        value: [
          "The Witch Doctor is a new character reminiscent of the Diablo II Necromancer",
          "The Barbarians will have a variety of revamped skills at their disposal based on the use of their incredible physical prowess.",
          "1-on-1 dueling system coming into play.",
          "Five new character classes, including the otherworldly Witch Doctor, or with re-imagined warriors from Diablo's past, like the powerful Barbarian",
          "Experience a new approach to in-game health as the previous reliance on mana and potions is appended by resource types unique to each class, as well as health globes",
          "In single player quests utilize up to three AI followers, from three different classes who can be equiped with basic items and leveled up",
          "Sell unique items found within the game for in-game gold or real money via online Auction House functionality",
          "The new Rune System in which skills and abilities are now automatically unlocked as you level",
        ],
      },
      { key: "format", value: ["DVD-ROM", "CD-ROM"] },
      { key: "genre", value: "adventure-game-genre" },
      { key: "hardwareplatform", value: "Pc" },
      { key: "isautographed", value: "0" },
      { key: "ismemorabilia", value: "0" },
      { key: "label", value: "Blizzard Entertainment" },
      { key: "manufacturer", value: "Blizzard Entertainment" },
      { key: "model", value: "728515" },
      { key: "mpn", value: "GACT-728515" },
      { key: "numberofitems", value: 1 },
      { key: "operatingsystem", value: "Windows 7" },
      { key: "packagequantity", value: "1" },
      { key: "partnumber", value: "GACT-728515" },
      {
        key: "platform",
        value: ["Windows Vista", "Windows XP", "Windows 7", "Mac OS X Intel"],
      },
      { key: "productgroup", value: "Video Games" },
      { key: "producttypename", value: "SOFTWARE_GAMES" },
      { key: "publisher", value: "Blizzard Entertainment" },
      { key: "releasedate", value: { $date: "2012-05-15T00:00:00.000+0200" } },
      { key: "studio", value: "Blizzard Entertainment" },
      { key: "title", value: "Diablo III - PC" },
      { key: "upc", value: "020626728515" },
      { key: "upclist", value: { UPCListElement: ["020626728515"] } },
    ],
    binding: "Computer Game",
    brand: "Blizzard Entertainment",
    catalognumberlist: { CatalogNumberListElement: ["020626728515", "72851"] },
    department: "mens",
    ean: "0020626728515",
    edition: "Standard",
    esrbagerating: "Mature",
    feature: [
      "The Witch Doctor is a new character reminiscent of the Diablo II Necromancer",
      "The Barbarians will have a variety of revamped skills at their disposal based on the use of their incredible physical prowess.",
      "1-on-1 dueling system coming into play.",
      "Five new character classes, including the otherworldly Witch Doctor, or with re-imagined warriors from Diablo's past, like the powerful Barbarian",
      "Experience a new approach to in-game health as the previous reliance on mana and potions is appended by resource types unique to each class, as well as health globes",
      "In single player quests utilize up to three AI followers, from three different classes who can be equiped with basic items and leveled up",
      "Sell unique items found within the game for in-game gold or real money via online Auction House functionality",
      "The new Rune System in which skills and abilities are now automatically unlocked as you level",
    ],
    format: ["DVD-ROM", "CD-ROM"],
    genre: "adventure-game-genre",
    hardwareplatform: "Pc",
    isautographed: "0",
    ismemorabilia: "0",
    label: "Blizzard Entertainment",
    price: 3999,
    currency: "USD",
    manufacturer: "Blizzard Entertainment",
    model: "728515",
    mpn: "GACT-728515",
    numberofitems: 1,
    operatingsystem: "Windows 7",
    packagequantity: "1",
    partnumber: "GACT-728515",
    platform: ["Windows Vista", "Windows XP", "Windows 7", "Mac OS X Intel"],
    productgroup: "Video Games",
    producttypename: "SOFTWARE_GAMES",
    publisher: "Blizzard Entertainment",
    releasedate: { $date: "2012-05-15T00:00:00.000+0200" },
    studio: "Blizzard Entertainment",
    title: "Diablo III - PC",
    upc: "020626728515",
    upclist: { UPCListElement: ["020626728515"] },
    category: "/games/pc",
    salesrank: 69,
  },
  {
    _id: { oid: "537f3aaac769230000be7e61" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/51Ba653B6ZL._SL75_.jpg",
        width: "53",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/51Ba653B6ZL._SL160_.jpg",
        width: "114",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/51Ba653B6ZL.jpg",
        width: "355",
        height: "500",
      },
    },
    description: [
      "Sethesda Softworks Fallout 3 GOTY Ed PCFallout 3 Game of the YearEdition PC",
    ],
    metadata: [
      { key: "binding", value: "DVD-ROM" },
      { key: "brand", value: "Bethesda" },
      {
        key: "catalognumberlist",
        value: { CatalogNumberListElement: ["12969"] },
      },
      { key: "ean", value: "0093155129696" },
      { key: "edition", value: "Game of the Year" },
      { key: "esrbagerating", value: "Mature" },
      {
        key: "feature",
        value: [
          "Take in the sights and sounds of the vast Capital Wasteland! See the great monuments of the United States lying in post-apocalyptic ruin!",
          "Vault-Tec engineers bring you the latest in human ability simulation - the SPECIAL Character System! Utilizing new breakthroughs in points-based ability representation, SPECIAL affords unlimited customization of your character.",
          "The wizards at Vault-Tec have done it again! No longer constrained to just one view, experience the world from 1st or 3rd person perspective.",
          "Feeling like a dastardly villain today, or a Good Samaritan? Pick a side or walk the line, as every situation can be dealt with in many different ways.",
          "Rain death and destruction in an all-new cinematic presentation featuring gory dismemberments and spectacular explosions.",
        ],
      },
      { key: "format", value: "DVD-ROM" },
      { key: "genre", value: "action_games" },
      { key: "hardwareplatform", value: "Pc" },
      { key: "isautographed", value: "0" },
      { key: "iseligiblefortradein", value: "1" },
      { key: "ismemorabilia", value: "0" },
      { key: "label", value: "Bethesda" },
      { key: "manufacturer", value: "Bethesda" },
      { key: "model", value: "12969" },
      { key: "mpn", value: "12969" },
      { key: "numberofitems", value: 1 },
      { key: "operatingsystem", value: "Windows Vista" },
      { key: "packagequantity", value: "1" },
      { key: "partnumber", value: "12969" },
      { key: "platform", value: ["Windows Vista", "Windows XP"] },
      { key: "productgroup", value: "Video Games" },
      { key: "producttypename", value: "SOFTWARE_GAMES" },
      { key: "publisher", value: "Bethesda" },
      { key: "releasedate", value: { $date: "2009-10-13T00:00:00.000+0200" } },
      { key: "studio", value: "Bethesda" },
      { key: "title", value: "Fallout 3: Game of The Year Edition (PC)" },
      { key: "upc", value: "093155129696" },
      { key: "upclist", value: { UPCListElement: ["093155129696"] } },
    ],
    binding: "DVD-ROM",
    brand: "Bethesda",
    catalognumberlist: { CatalogNumberListElement: ["12969"] },
    ean: "0093155129696",
    edition: "Game of the Year",
    esrbagerating: "Mature",
    feature: [
      "Take in the sights and sounds of the vast Capital Wasteland! See the great monuments of the United States lying in post-apocalyptic ruin!",
      "Vault-Tec engineers bring you the latest in human ability simulation - the SPECIAL Character System! Utilizing new breakthroughs in points-based ability representation, SPECIAL affords unlimited customization of your character.",
      "The wizards at Vault-Tec have done it again! No longer constrained to just one view, experience the world from 1st or 3rd person perspective.",
      "Feeling like a dastardly villain today, or a Good Samaritan? Pick a side or walk the line, as every situation can be dealt with in many different ways.",
      "Rain death and destruction in an all-new cinematic presentation featuring gory dismemberments and spectacular explosions.",
    ],
    format: "DVD-ROM",
    genre: "action_games",
    hardwareplatform: "Pc",
    isautographed: "0",
    iseligiblefortradein: "1",
    ismemorabilia: "0",
    label: "Bethesda",
    price: 1999,
    currency: "USD",
    manufacturer: "Bethesda",
    model: "12969",
    mpn: "12969",
    numberofitems: 1,
    operatingsystem: "Windows Vista",
    packagequantity: "1",
    partnumber: "12969",
    platform: ["Windows Vista", "Windows XP"],
    productgroup: "Video Games",
    producttypename: "SOFTWARE_GAMES",
    publisher: "Bethesda",
    releasedate: { $date: "2009-10-13T00:00:00.000+0200" },
    studio: "Bethesda",
    title: "Fallout 3: Game of The Year Edition (PC)",
    upc: "093155129696",
    upclist: { UPCListElement: ["093155129696"] },
    category: "/games/pc",
    salesrank: 1229,
  },
  {
    _id: { oid: "537f3aaac769230000be7e62" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/51DeQeU7MiL._SL75_.jpg",
        width: "53",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/51DeQeU7MiL._SL160_.jpg",
        width: "113",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/51DeQeU7MiL.jpg",
        width: "354",
        height: "500",
      },
    },
    description: [
      "The Elder Scrolls V: Skyrim is the next installment in the award-winning Elder Scrolls series. Skyrim is the follow up to the 2006 Game of the Year, The Elder Scrolls IV: Oblivion and the next game from Bethesda Game Studios, creators of the 2008 Game of the Year, Fallout 3.",
    ],
    metadata: [
      { key: "binding", value: "DVD-ROM" },
      { key: "brand", value: "Bethesda" },
      {
        key: "catalognumberlist",
        value: { CatalogNumberListElement: ["11761"] },
      },
      { key: "color", value: "One Color" },
      { key: "ean", value: "0093155117617" },
      { key: "edition", value: "Standard" },
      { key: "esrbagerating", value: "Mature" },
      {
        key: "feature",
        value: [
          "Skyrim reimagines the open-world fantasy epic, pushing the game play and technology of a virtual world to new heights",
          "Play any type of character you can imagine, and do whatever you want; the legendary freedom of choice, storytelling",
          "Skyrim's new game engine brings to life a complete virtual world with rolling clouds, rugged mountains, bustling cities, lush fields",
          "Choose from hundreds of weapons, spells, and abilities; the new character system allows you to play any way you want",
          "Requires internet connection and free steam account to activate",
        ],
      },
      { key: "format", value: "DVD-ROM" },
      { key: "genre", value: "role_playing_games" },
      { key: "hardwareplatform", value: "Pc" },
      { key: "isadultproduct", value: "0" },
      { key: "isautographed", value: "0" },
      { key: "ismemorabilia", value: "0" },
      { key: "label", value: "Bethesda Softworks" },
      { key: "manufacturer", value: "Bethesda Softworks" },
      { key: "model", value: "11761" },
      { key: "mpn", value: "11761" },
      { key: "numberofitems", value: 1 },
      { key: "operatingsystem", value: "Windows Vista" },
      { key: "packagequantity", value: "1" },
      { key: "partnumber", value: "11761" },
      { key: "platform", value: ["Windows XP", "Windows Vista", "Windows 7"] },
      { key: "productgroup", value: "Video Games" },
      { key: "producttypename", value: "SOFTWARE_GAMES" },
      { key: "publisher", value: "Bethesda Softworks" },
      { key: "releasedate", value: { $date: "2011-11-11T00:00:00.000+0100" } },
      { key: "size", value: "One Size" },
      { key: "sku", value: "BIN-ElderScrollsVSkyrimPC" },
      { key: "studio", value: "Bethesda Softworks" },
      { key: "title", value: "Elder Scrolls V: Skyrim - PC" },
      { key: "upc", value: "093155117617" },
      { key: "upclist", value: { UPCListElement: ["093155117617"] } },
    ],
    binding: "DVD-ROM",
    brand: "Bethesda",
    catalognumberlist: { CatalogNumberListElement: ["11761"] },
    color: "One Color",
    ean: "0093155117617",
    edition: "Standard",
    esrbagerating: "Mature",
    feature: [
      "Skyrim reimagines the open-world fantasy epic, pushing the game play and technology of a virtual world to new heights",
      "Play any type of character you can imagine, and do whatever you want; the legendary freedom of choice, storytelling",
      "Skyrim's new game engine brings to life a complete virtual world with rolling clouds, rugged mountains, bustling cities, lush fields",
      "Choose from hundreds of weapons, spells, and abilities; the new character system allows you to play any way you want",
      "Requires internet connection and free steam account to activate",
    ],
    format: "DVD-ROM",
    genre: "role_playing_games",
    hardwareplatform: "Pc",
    isadultproduct: "0",
    isautographed: "0",
    ismemorabilia: "0",
    label: "Bethesda Softworks",
    price: 1999,
    currency: "USD",
    manufacturer: "Bethesda Softworks",
    model: "11761",
    mpn: "11761",
    numberofitems: 1,
    operatingsystem: "Windows Vista",
    packagequantity: "1",
    partnumber: "11761",
    platform: ["Windows XP", "Windows Vista", "Windows 7"],
    productgroup: "Video Games",
    producttypename: "SOFTWARE_GAMES",
    publisher: "Bethesda Softworks",
    releasedate: { $date: "2011-11-11T00:00:00.000+0100" },
    size: "One Size",
    sku: "BIN-ElderScrollsVSkyrimPC",
    studio: "Bethesda Softworks",
    title: "Elder Scrolls V: Skyrim - PC",
    upc: "093155117617",
    upclist: { UPCListElement: ["093155117617"] },
    category: "/games/pc",
    salesrank: 845,
  },
  {
    _id: { oid: "537f3aaac769230000be7e63" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/31NhIzIMrUL._SL75_.jpg",
        width: "75",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/31NhIzIMrUL._SL160_.jpg",
        width: "160",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/31NhIzIMrUL.jpg",
        width: "400",
        height: "400",
      },
    },
    description: [
      "<br>This controller is of the highest quality and it can be used with a PS3 or a PC. No installation required, just plug and play.\n<br>\n<br>Features: Super Comfort Grip, Effective Button Action, Non-slip Handles, 4-way Button, 2 Analog Joysticks, 2 Vibration Feedback Motors, PS and Select Buttons, L1 and L2 Buttons, R1 and R2 Buttons, USB Cable included.<br>\n\n<br>Does not have any tilt sensing capabilities. It is not a certified Sony PS3 controller<br>\n\n<br>Package Contents:<br>\n<br>\n1x PS3 Dual Shock Controller",
    ],
    metadata: [
      { key: "binding", value: "Video Game" },
      { key: "brand", value: "Gator Crunch" },
      { key: "ean", value: "0817946010440" },
      {
        key: "feature",
        value: [
          "USB Game Controller - Works with both PS3 and PC",
          "Save money using a wired controller",
          "Ideal for the price aware consumer",
          "Lifetime warranty",
          "Gator Crunch - Quality you know and trust",
        ],
      },
      { key: "hardwareplatform", value: "Pc" },
      { key: "label", value: "Gator Crunch" },
      { key: "manufacturer", value: "Gator Crunch" },
      { key: "model", value: "GC-PS3WCUSB" },
      { key: "operatingsystem", value: "PlayStation 3" },
      { key: "packagequantity", value: "1" },
      { key: "platform", value: "PlayStation 3" },
      { key: "productgroup", value: "Video Games" },
      { key: "producttypename", value: "VIDEO_GAME_ACCESSORIES" },
      { key: "publisher", value: "Gator Crunch" },
      { key: "studio", value: "Gator Crunch" },
      {
        key: "title",
        value:
          "Game Controller for PC or PlayStation 3 (PS3) - (Lifetime Warranty, Bulk Packaging)",
      },
      { key: "upc", value: "817946010440" },
      { key: "upclist", value: { UPCListElement: ["817946010440"] } },
    ],
    binding: "Video Game",
    brand: "Gator Crunch",
    ean: "0817946010440",
    feature: [
      "USB Game Controller - Works with both PS3 and PC",
      "Save money using a wired controller",
      "Ideal for the price aware consumer",
      "Lifetime warranty",
      "Gator Crunch - Quality you know and trust",
    ],
    hardwareplatform: "Pc",
    label: "Gator Crunch",
    price: 2999,
    currency: "USD",
    manufacturer: "Gator Crunch",
    model: "GC-PS3WCUSB",
    operatingsystem: "PlayStation 3",
    packagequantity: "1",
    platform: "PlayStation 3",
    productgroup: "Video Games",
    producttypename: "VIDEO_GAME_ACCESSORIES",
    publisher: "Gator Crunch",
    studio: "Gator Crunch",
    title:
      "Game Controller for PC or PlayStation 3 (PS3) - (Lifetime Warranty, Bulk Packaging)",
    upc: "817946010440",
    upclist: { UPCListElement: ["817946010440"] },
    category: "/games/pc",
    salesrank: 675,
  },
  {
    _id: { oid: "537f3aaac769230000be7e64" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/416xeHGXbUL._SL75_.jpg",
        width: "53",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/416xeHGXbUL._SL160_.jpg",
        width: "113",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/416xeHGXbUL.jpg",
        width: "352",
        height: "500",
      },
    },
    description: [
      'Pushing the boundaries of what fans have come to expect from the record-setting entertainment franchise, Call of Duty: Black Ops II propels players into a near future, 21st Century Cold War, where technology and weapons have converged to create a new generation of warfare.<br /><strong><br /><em>Call of Duty: Black Ops II</em> Gamescom Accolades</strong><br />  <ul> <li>"The most ambitious<em> Call of Duty</em> to date" - USA Today</li> <li>"Poised to blow you away" - G4</li> <li>"Treyarch has just vaulted Black Ops II to a new level" - Joystiq</li> <li>"<em>Black Ops II</em> is changing multiplayer.  A lot." - Kotaku</li> <li>"A bold departure" - IGN</li> <li>"A whole new level of competitive gaming" - MTV</li> <li>"Brilliant visuals and adrenaline-inducing gameplay" - Forbes</li> <li>"Best of Gamescom" - Gamespot</li> </ul>',
    ],
    metadata: [
      { key: "binding", value: "DVD-ROM" },
      { key: "brand", value: "Activision" },
      {
        key: "catalognumberlist",
        value: { CatalogNumberListElement: ["047875333499", "33349"] },
      },
      { key: "ceroagerating", value: "Only Suitable for 18 years and over" },
      { key: "ean", value: "0047875333499" },
      { key: "edition", value: "Standard" },
      { key: "esrbagerating", value: "Mature" },
      {
        key: "feature",
        value: [
          "An all-new Call of Duty - Black Ops storyline featuring new characters and returning characters",
          "Unique single-player campaign that contains two time periods linked by characters and their actions",
          "Special Strike Force missions, in which the players action affect the outcome of gameplay and the overall campaign",
          "Variety of multiplayer modes and play options",
        ],
      },
      { key: "format", value: "DVD-ROM" },
      { key: "genre", value: "adventure-game-genre" },
      { key: "hardwareplatform", value: "Pc" },
      { key: "isadultproduct", value: "0" },
      { key: "isautographed", value: "0" },
      { key: "ismemorabilia", value: "0" },
      { key: "label", value: "Activision" },
      { key: "manufacturer", value: "Activision" },
      { key: "model", value: "33349" },
      { key: "mpn", value: "33349" },
      { key: "numberofitems", value: 1 },
      { key: "operatingsystem", value: "Windows 7" },
      { key: "packagequantity", value: "1" },
      { key: "partnumber", value: "33349" },
      { key: "platform", value: ["Windows Vista", "Windows 7"] },
      { key: "productgroup", value: "Video Games" },
      { key: "producttypename", value: "SOFTWARE_GAMES" },
      { key: "publisher", value: "Activision" },
      { key: "regioncode", value: "19696" },
      { key: "releasedate", value: { $date: "2012-11-13T00:00:00.000+0100" } },
      { key: "sku", value: "ACI 33349" },
      { key: "studio", value: "Activision" },
      { key: "title", value: "Call of Duty: Black Ops II - PC" },
      { key: "upc", value: "047875333499" },
      { key: "upclist", value: { UPCListElement: ["047875333499"] } },
    ],
    binding: "DVD-ROM",
    brand: "Activision",
    catalognumberlist: { CatalogNumberListElement: ["047875333499", "33349"] },
    ceroagerating: "Only Suitable for 18 years and over",
    ean: "0047875333499",
    edition: "Standard",
    esrbagerating: "Mature",
    feature: [
      "An all-new Call of Duty - Black Ops storyline featuring new characters and returning characters",
      "Unique single-player campaign that contains two time periods linked by characters and their actions",
      "Special Strike Force missions, in which the players action affect the outcome of gameplay and the overall campaign",
      "Variety of multiplayer modes and play options",
    ],
    format: "DVD-ROM",
    genre: "adventure-game-genre",
    hardwareplatform: "Pc",
    isadultproduct: "0",
    isautographed: "0",
    ismemorabilia: "0",
    label: "Activision",
    price: 5999,
    currency: "USD",
    manufacturer: "Activision",
    model: "33349",
    mpn: "33349",
    numberofitems: 1,
    operatingsystem: "Windows 7",
    packagequantity: "1",
    partnumber: "33349",
    platform: ["Windows Vista", "Windows 7"],
    productgroup: "Video Games",
    producttypename: "SOFTWARE_GAMES",
    publisher: "Activision",
    regioncode: "19696",
    releasedate: { $date: "2012-11-13T00:00:00.000+0100" },
    sku: "ACI 33349",
    studio: "Activision",
    title: "Call of Duty: Black Ops II - PC",
    upc: "047875333499",
    upclist: { UPCListElement: ["047875333499"] },
    category: "/games/pc",
    salesrank: 1745,
  },
  {
    _id: { oid: "537f3aaac769230000be7e65" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/51N7GT9BQ%2BL._SL75_.jpg",
        width: "53",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/51N7GT9BQ%2BL._SL160_.jpg",
        width: "113",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/51N7GT9BQ%2BL.jpg",
        width: "354",
        height: "500",
      },
    },
    description: [
      "The award-winning developer Crytek is back with Crysis 3, the first blockbuster shooter of 2013! Return to the fight as Prophet, the Nanosuit soldier on a quest to rediscover his humanity and exact brutal revenge. Adapt on the fly with the stealth and armor abilities of your unique Nanosuit as you battle through the seven wonders of New York's Liberty Dome. Unleash the firepower of your all-new, high-tech bow and alien weaponry to hunt both human and alien enemies. And uncover the truth behind the death of your squad while reestablishing the power of human will in a rich story full of exciting twists and turns. Crysis 3 is the ultimate sandbox shooter, realized in the stunning visuals only Crytek and the latest version of CryENGINE can deliver. Assess Adapt, and Attack starting Spring 2013.",
    ],
    metadata: [
      { key: "binding", value: "DVD-ROM" },
      { key: "brand", value: "Electronic Arts" },
      {
        key: "catalognumberlist",
        value: { CatalogNumberListElement: ["884095145798", "0000000002"] },
      },
      { key: "ean", value: "0014633198102" },
      { key: "edition", value: "Standard" },
      { key: "esrbagerating", value: "Mature" },
      {
        key: "feature",
        value: [
          "Seven Wonders of the Urban Rainforest - New York City has been contained in a giant nanodome and grown into a unique rainforest with seven distinct environments. Master the ultimate sandbox and turn it into your own personal hunting ground.",
          "Assess, Adapt, and Attack - Crysis's highly-acclaimed sandbox gameplay is back with more open levels to let players choose their path and approach. Your upgraded Nanosuit allows brute force or stealth, always giving you more than one option.",
          "Expanded Multiplayer - Experiment with new ways to customize your Nanosuit and brand new game modes.",
          "The Biggest and Most Explosive Arsenal in Franchise History - In addition to giving you an arsenal of human firearms, Crysis 3 lets you scavenge alien weapons and deploy an all-new signature bow",
          "The Evolution of CryENGINE - CryENGINE unleashes the power of the Crytek creative team and delivers a visually stunning and varied gameplay experience.",
        ],
      },
      { key: "format", value: "DVD-ROM" },
      { key: "genre", value: "action_games" },
      { key: "hardwareplatform", value: "Pc" },
      { key: "isautographed", value: "0" },
      { key: "ismemorabilia", value: "0" },
      { key: "label", value: "Electronic Arts" },
      { key: "manufacturer", value: "Electronic Arts" },
      { key: "model", value: "19810" },
      { key: "mpn", value: "19810" },
      { key: "numberofitems", value: 1 },
      { key: "operatingsystem", value: "Windows Vista" },
      { key: "packagequantity", value: "1" },
      { key: "partnumber", value: "19810" },
      { key: "platform", value: ["Windows Vista", "Windows XP"] },
      { key: "productgroup", value: "Video Games" },
      { key: "producttypename", value: "SOFTWARE_GAMES" },
      {
        key: "publicationdate",
        value: { $date: "2013-02-19T00:00:00.000+0100" },
      },
      { key: "publisher", value: "Electronic Arts" },
      { key: "regioncode", value: "23576" },
      { key: "releasedate", value: { $date: "2013-02-19T00:00:00.000+0100" } },
      { key: "studio", value: "Electronic Arts" },
      { key: "title", value: "Crysis 3 - PC" },
      { key: "upc", value: "132017948157" },
      {
        key: "upclist",
        value: {
          UPCListElement: [
            "132017948157",
            "884095145798",
            "014633198102",
            "904095157932",
          ],
        },
      },
    ],
    binding: "DVD-ROM",
    brand: "Electronic Arts",
    catalognumberlist: {
      CatalogNumberListElement: ["884095145798", "0000000002"],
    },
    ean: "0014633198102",
    edition: "Standard",
    esrbagerating: "Mature",
    feature: [
      "Seven Wonders of the Urban Rainforest - New York City has been contained in a giant nanodome and grown into a unique rainforest with seven distinct environments. Master the ultimate sandbox and turn it into your own personal hunting ground.",
      "Assess, Adapt, and Attack - Crysis's highly-acclaimed sandbox gameplay is back with more open levels to let players choose their path and approach. Your upgraded Nanosuit allows brute force or stealth, always giving you more than one option.",
      "Expanded Multiplayer - Experiment with new ways to customize your Nanosuit and brand new game modes.",
      "The Biggest and Most Explosive Arsenal in Franchise History - In addition to giving you an arsenal of human firearms, Crysis 3 lets you scavenge alien weapons and deploy an all-new signature bow",
      "The Evolution of CryENGINE - CryENGINE unleashes the power of the Crytek creative team and delivers a visually stunning and varied gameplay experience.",
    ],
    format: "DVD-ROM",
    genre: "action_games",
    hardwareplatform: "Pc",
    isautographed: "0",
    ismemorabilia: "0",
    label: "Electronic Arts",
    price: 5999,
    currency: "USD",
    manufacturer: "Electronic Arts",
    model: "19810",
    mpn: "19810",
    numberofitems: 1,
    operatingsystem: "Windows Vista",
    packagequantity: "1",
    partnumber: "19810",
    platform: ["Windows Vista", "Windows XP"],
    productgroup: "Video Games",
    producttypename: "SOFTWARE_GAMES",
    publicationdate: { $date: "2013-02-19T00:00:00.000+0100" },
    publisher: "Electronic Arts",
    regioncode: "23576",
    releasedate: { $date: "2013-02-19T00:00:00.000+0100" },
    studio: "Electronic Arts",
    title: "Crysis 3 - PC",
    upc: "132017948157",
    upclist: {
      UPCListElement: [
        "132017948157",
        "884095145798",
        "014633198102",
        "904095157932",
      ],
    },
    category: "/games/pc",
    salesrank: 980,
  },
  {
    _id: { oid: "537f3aaac769230000be7e66" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/418h3hauXWL._SL75_.jpg",
        width: "75",
        height: "57",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/418h3hauXWL._SL160_.jpg",
        width: "160",
        height: "122",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/418h3hauXWL.jpg",
        width: "500",
        height: "380",
      },
    },
    description: [
      "Precisely what you need for PC and Xbox gaming. Play with confidence with this responsive, ergonomic controller. It works on either your PC or Xbox to give you the ultimate gaming experience.",
    ],
    metadata: [
      { key: "binding", value: "Personal Computers" },
      { key: "brand", value: "Microsoft" },
      {
        key: "catalognumberlist",
        value: {
          CatalogNumberListElement: [
            "52A-00004",
            "QA73-52A-00004",
            "885370239393",
            "4670541",
          ],
        },
      },
      { key: "color", value: "Black" },
      { key: "ean", value: "0885370239393" },
      { key: "esrbagerating", value: "Rating Pending" },
      {
        key: "feature",
        value: [
          "Play in comfort - A compact, ergonomic shape lets you play comfortably for hours on your PC.",
          "Feel the action - Vibration feedback gives you a riveting gaming experience.",
          "PC gaming at its best - Precise thumb sticks, two pressure-point triggers, and an 8-way directional pad help you stay in control.",
          "Feel the action - Vibration feedback gives you a riveting gaming experience. Powered USB port",
          "PC gaming at its best - Precise thumb sticks, two pressure-point triggers, and an 8-way directional pad help you stay in control",
        ],
      },
      { key: "format", value: "CD-ROM" },
      { key: "genre", value: "action-games" },
      { key: "hardwareplatform", value: "pc" },
      { key: "isautographed", value: "0" },
      { key: "ismemorabilia", value: "0" },
      { key: "label", value: "Microsoft" },
      {
        key: "legaldisclaimer",
        value: "This product upon sale is final. No returns or money back.",
      },
      { key: "manufacturer", value: "Microsoft" },
      { key: "model", value: "52A-00004" },
      { key: "mpn", value: "52A-00004" },
      { key: "numberofitems", value: 1 },
      { key: "operatingsystem", value: "N/A" },
      { key: "packagequantity", value: "1" },
      { key: "partnumber", value: "52A-00004" },
      { key: "platform", value: "Xbox 360" },
      { key: "productgroup", value: "CE" },
      { key: "producttypename", value: "COMPUTER_INPUT_DEVICE" },
      { key: "publisher", value: "Microsoft" },
      { key: "sku", value: "MIC52A00004" },
      { key: "studio", value: "Microsoft" },
      { key: "title", value: "Microsoft Xbox 360 Controller for Windows" },
      { key: "upc", value: "885370239393" },
      { key: "upclist", value: { UPCListElement: ["885370239393"] } },
    ],
    binding: "Personal Computers",
    brand: "Microsoft",
    catalognumberlist: {
      CatalogNumberListElement: [
        "52A-00004",
        "QA73-52A-00004",
        "885370239393",
        "4670541",
      ],
    },
    color: "Black",
    ean: "0885370239393",
    esrbagerating: "Rating Pending",
    feature: [
      "Play in comfort - A compact, ergonomic shape lets you play comfortably for hours on your PC.",
      "Feel the action - Vibration feedback gives you a riveting gaming experience.",
      "PC gaming at its best - Precise thumb sticks, two pressure-point triggers, and an 8-way directional pad help you stay in control.",
      "Feel the action - Vibration feedback gives you a riveting gaming experience. Powered USB port",
      "PC gaming at its best - Precise thumb sticks, two pressure-point triggers, and an 8-way directional pad help you stay in control",
    ],
    format: "CD-ROM",
    genre: "action-games",
    hardwareplatform: "pc",
    isautographed: "0",
    ismemorabilia: "0",
    label: "Microsoft",
    legaldisclaimer:
      "This product upon sale is final. No returns or money back.",
    price: 3995,
    currency: "USD",
    manufacturer: "Microsoft",
    model: "52A-00004",
    mpn: "52A-00004",
    numberofitems: 1,
    operatingsystem: "N/A",
    packagequantity: "1",
    partnumber: "52A-00004",
    platform: "Xbox 360",
    productgroup: "CE",
    producttypename: "COMPUTER_INPUT_DEVICE",
    publisher: "Microsoft",
    sku: "MIC52A00004",
    studio: "Microsoft",
    title: "Microsoft Xbox 360 Controller for Windows",
    upc: "885370239393",
    upclist: { UPCListElement: ["885370239393"] },
    category: "/games/pc",
    salesrank: 0,
  },
  {
    _id: { oid: "537f3aaac769230000be7e67" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/517S6KnRpOL._SL75_.jpg",
        width: "53",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/517S6KnRpOL._SL160_.jpg",
        width: "113",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/517S6KnRpOL.jpg",
        width: "353",
        height: "500",
      },
    },
    description: [
      "Electronic Arts Spore PC - Win/Mac title Spore PC - Win/Mac",
    ],
    metadata: [
      { key: "binding", value: "DVD-ROM" },
      { key: "brand", value: "Electronic Arts" },
      {
        key: "catalognumberlist",
        value: { CatalogNumberListElement: ["014633153521", "15352"] },
      },
      { key: "ean", value: "0014633153521" },
      { key: "edition", value: "Standard" },
      { key: "esrbagerating", value: "Everyone 10+" },
      {
        key: "feature",
        value: [
          "Epic journey from the origin and evolution of life through the development of civilization and technology and outer space exploration",
          "Play any way you choose in the five evolutionary phases of Spore: Cell, Creature, Tribe, Civilization, and Space",
          "Grow, evolve, interact with and battle other cultures, and conquer the planet",
          "Visit literally millions of planets full of other player's creations",
          "Single-player game provides unlimited worlds to explore and play",
        ],
      },
      { key: "format", value: "DVD-ROM" },
      { key: "genre", value: "artificial_life_simulation_games" },
      { key: "hardwareplatform", value: "Mac" },
      { key: "isautographed", value: "0" },
      { key: "iseligiblefortradein", value: "1" },
      { key: "ismemorabilia", value: "0" },
      { key: "label", value: "Electronic Arts" },
      { key: "manufacturer", value: "Electronic Arts" },
      { key: "model", value: "15352" },
      { key: "mpn", value: "15352" },
      { key: "numberofdiscs", value: "1" },
      { key: "numberofitems", value: 1 },
      { key: "operatingsystem", value: "Windows 2000" },
      { key: "packagequantity", value: "1" },
      { key: "partnumber", value: "15352" },
      { key: "platform", value: ["Windows Vista", "Mac", "Windows XP"] },
      { key: "productgroup", value: "Video Games" },
      { key: "producttypename", value: "SOFTWARE_GAMES" },
      { key: "publisher", value: "Electronic Arts" },
      { key: "releasedate", value: { $date: "2008-09-07T00:00:00.000+0200" } },
      { key: "studio", value: "Electronic Arts" },
      { key: "title", value: "Spore - PC/Mac" },
      { key: "upc", value: "014633153521" },
      { key: "upclist", value: { UPCListElement: ["014633153521"] } },
    ],
    binding: "DVD-ROM",
    brand: "Electronic Arts",
    catalognumberlist: { CatalogNumberListElement: ["014633153521", "15352"] },
    ean: "0014633153521",
    edition: "Standard",
    esrbagerating: "Everyone 10+",
    feature: [
      "Epic journey from the origin and evolution of life through the development of civilization and technology and outer space exploration",
      "Play any way you choose in the five evolutionary phases of Spore: Cell, Creature, Tribe, Civilization, and Space",
      "Grow, evolve, interact with and battle other cultures, and conquer the planet",
      "Visit literally millions of planets full of other player's creations",
      "Single-player game provides unlimited worlds to explore and play",
    ],
    format: "DVD-ROM",
    genre: "artificial_life_simulation_games",
    hardwareplatform: "Mac",
    isautographed: "0",
    iseligiblefortradein: "1",
    ismemorabilia: "0",
    label: "Electronic Arts",
    price: 1999,
    currency: "USD",
    manufacturer: "Electronic Arts",
    model: "15352",
    mpn: "15352",
    numberofdiscs: "1",
    numberofitems: 1,
    operatingsystem: "Windows 2000",
    packagequantity: "1",
    partnumber: "15352",
    platform: ["Windows Vista", "Mac", "Windows XP"],
    productgroup: "Video Games",
    producttypename: "SOFTWARE_GAMES",
    publisher: "Electronic Arts",
    releasedate: { $date: "2008-09-07T00:00:00.000+0200" },
    studio: "Electronic Arts",
    title: "Spore - PC/Mac",
    upc: "014633153521",
    upclist: { UPCListElement: ["014633153521"] },
    category: "/games/pc",
    salesrank: 1028,
  },
  {
    _id: { oid: "537f3aaac769230000be7e68" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/51UfXhiC61L._SL75_.jpg",
        width: "57",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/51UfXhiC61L._SL160_.jpg",
        width: "121",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/51UfXhiC61L.jpg",
        width: "377",
        height: "500",
      },
    },
    description: [
      '<div class="aplus"> <h5> <div id="header0">Outnumbered and Outgunned, but Not Outmatched</div> </h5> <div class="a-spacing-small" id="text0"> <p>Call of Duty: Ghosts is an extraordinary step forward for one of the largest entertainment franchises of all-time. This new chapter in the Call of Duty franchise features a new dynamic where players are on the side of a crippled nation fighting not for freedom, or liberty, but simply to survive. Fueling this all new Call of Duty experience, the franchise’s new next-gen engine delivers stunning levels of immersion and performance, all while maintaining the speed and fluidity of 60 frames-per-second across all platforms.</p> </div> <div class="two-third-col"> <div class="leftImage" style="width: 300px;"> <div id="image0"><img src="http://ecx.images-amazon.com/images/I/313KzKorf3L.jpg" /></div> </div> <div class="leftImage" style="width: 300px;"> <div id="image1"><img src="http://ecx.images-amazon.com/images/I/31qJgKmg8vL.jpg" /></div> </div> <h5> <div id="header1">Single Player Campaign</div> </h5> <div class="a-spacing-small" id="text1"> <p>Ten years after a devastating mass event, America’s borders and the balance of global power have changed forever. As what’s left of the nation’s Special Operations forces, a mysterious group known only as “Ghosts” leads the fight back against a newly emerged, technologically-superior global power. A New Call of Duty Universe: For the first time in franchise history, players will take on the underdog role with Call of Duty: Ghosts; outnumbered and outgunned, players must fight to reclaim a fallen nation in an intensely personal narrative. Gamers will get to know an entirely new cast of characters and visit locales in a changed world unlike anything seen in Call of Duty before.</p> </div> <h5> <div id="header2">Multiplayer</div> </h5> <div class="a-spacing-small" id="text2"> <p>In Call of Duty: Ghosts you don’t just create a class, you create a soldier, a first for the franchise. In the new Create-A-Soldier system, players can change the physical appearance of their soldier by choosing the head, body type, head-gear and equipment, and for the first time in a Call of Duty game, the player can also choose their gender. With 20,000 possible combinations, this is the most flexible and comprehensive character customization in Call of Duty history. New dynamic maps are the evolution of multiplayer. They include interactive elements and player triggered events that make the environment evolve as each match goes on. The entire landscape can shift and force players to change tactics and strategies. Call of Duty: Ghosts introduces new tactical player movements. The new contextual lean system now allows players to lean around obstacles without adding button combinations or fully leaving cover. The new mantling system allows fluid movement over objects, while maintaining momentum. The knee slide allows for a natural transition from sprinting crouching to prone. Call of Duty: Ghosts delivers over 20 NEW Kill Streaks in Call of Duty: Ghosts - such as Juggernaut Maniac, the Helo Scout, the Vulture and the ODIN Strike. Players can even bring in guard dog Riley, from the single-player campaign, to protect and also to attack enemies. There are also over 30 NEW weapons, including an entirely new weapon class: Marksman Rifles.</p> </div> <h5> <div id="header3">Squads</div> </h5> <div class="a-spacing-small" id="text3"> <p>Build your team and take up to 6 of them into battle in the all new Squads mode. This mode takes the best parts of the multiplayer experience and allows you to play either solo or cooperatively with the custom soldiers created and leveled up in multiplayer. The load-out choices you make for your Squad members will directly change the AI behavior of your squad-mates. Give your soldier a sniper rifle and he’ll behave like a sniper, and an SMG guy will be more run and gun.</p> </div> <h5> <div id="header4"></div> </h5> <div class="a-spacing-small" id="text4"></div> </div> <div class="third-col last"> <div class="leftImage" style="width: 300px;"> <div id="image2"><img src="http://ecx.images-amazon.com/images/I/31vtpqIpllL.jpg" /></div> </div> <div class="break"></div> <h5> <div id="header5">Extinction</div> </h5> <div class="a-spacing-small" id="text5"> <p>A completely new one to four player, co-op game mode featuring a unique blend of fast-paced survival gameplay, base defense, player customization and class leveling. Teamwork and communication are essential when playing Extinction, as your team faces an inhuman menace that has overrun an isolated Colorado town and you must eliminate the threat via any means necessary.</p> </div> <br /> <h5> <div id="header6"></div> </h5> <div id="list0"></div> </div> </div>',
    ],
    metadata: [
      { key: "binding", value: "Video Game" },
      { key: "brand", value: "Activision" },
      {
        key: "catalognumberlist",
        value: { CatalogNumberListElement: ["33451"] },
      },
      { key: "department", value: "Video Games" },
      { key: "ean", value: "0047875334519" },
      { key: "edition", value: "Standard" },
      { key: "esrbagerating", value: "Mature" },
      {
        key: "feature",
        value: [
          "Next-gen engine ushers in an unprecedented level of innovation, delivering stunning and lifelike characters, gorgeously rendered environments, and authentic real-world animations, all brought to life by advanced lighting systems and visual effects",
          "Players will take on the underdog role with Call of Duty - Ghosts; outnumbered and outgunned, players must fight to reclaim a fallen nation in an intensely personal narrative. Gamers will get to know an entirely new cast of characters and locales in a world unlike any that Call of Duty has explored before",
          "Dynamic maps bring earthquakes, floods, and user-initiated events that fundamentally alter the flow and strategy of every fight",
          "Unparalleled character customization, players have total control to tailor-make their soldier",
        ],
      },
      { key: "format", value: "DVD-ROM" },
      { key: "genre", value: "shooter-action-game-genre" },
      { key: "hardwareplatform", value: "Pc" },
      { key: "isautographed", value: "0" },
      { key: "ismemorabilia", value: "0" },
      { key: "label", value: "Activision" },
      { key: "manufacturer", value: "Activision" },
      { key: "model", value: "33451" },
      { key: "mpn", value: "33451" },
      { key: "numberofitems", value: 1 },
      { key: "operatingsystem", value: "Windows 7" },
      { key: "packagequantity", value: "1" },
      { key: "partnumber", value: "33451" },
      { key: "platform", value: "Windows 7" },
      { key: "productgroup", value: "Video Games" },
      { key: "producttypename", value: "SOFTWARE_GAMES" },
      { key: "publisher", value: "Activision" },
      { key: "regioncode", value: "19697" },
      { key: "releasedate", value: { $date: "2013-11-05T00:00:00.000+0100" } },
      { key: "studio", value: "Activision" },
      { key: "title", value: "Call of Duty: Ghosts - PC" },
      { key: "upc", value: "047875334519" },
      { key: "upclist", value: { UPCListElement: ["047875334519"] } },
    ],
    binding: "Video Game",
    brand: "Activision",
    catalognumberlist: { CatalogNumberListElement: ["33451"] },
    department: "Video Games",
    ean: "0047875334519",
    edition: "Standard",
    esrbagerating: "Mature",
    feature: [
      "Next-gen engine ushers in an unprecedented level of innovation, delivering stunning and lifelike characters, gorgeously rendered environments, and authentic real-world animations, all brought to life by advanced lighting systems and visual effects",
      "Players will take on the underdog role with Call of Duty - Ghosts; outnumbered and outgunned, players must fight to reclaim a fallen nation in an intensely personal narrative. Gamers will get to know an entirely new cast of characters and locales in a world unlike any that Call of Duty has explored before",
      "Dynamic maps bring earthquakes, floods, and user-initiated events that fundamentally alter the flow and strategy of every fight",
      "Unparalleled character customization, players have total control to tailor-make their soldier",
    ],
    format: "DVD-ROM",
    genre: "shooter-action-game-genre",
    hardwareplatform: "Pc",
    isautographed: "0",
    ismemorabilia: "0",
    label: "Activision",
    price: 5999,
    currency: "USD",
    manufacturer: "Activision",
    model: "33451",
    mpn: "33451",
    numberofitems: 1,
    operatingsystem: "Windows 7",
    packagequantity: "1",
    partnumber: "33451",
    platform: "Windows 7",
    productgroup: "Video Games",
    producttypename: "SOFTWARE_GAMES",
    publisher: "Activision",
    regioncode: "19697",
    releasedate: { $date: "2013-11-05T00:00:00.000+0100" },
    studio: "Activision",
    title: "Call of Duty: Ghosts - PC",
    upc: "047875334519",
    upclist: { UPCListElement: ["047875334519"] },
    category: "/games/pc",
    salesrank: 1425,
  },
  {
    _id: { oid: "537f3aaac769230000be7e69" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/51i1Xy1BxHL._SL75_.jpg",
        width: "75",
        height: "70",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/51i1Xy1BxHL._SL160_.jpg",
        width: "160",
        height: "149",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/51i1Xy1BxHL.jpg",
        width: "500",
        height: "467",
      },
    },
    description: [
      "Assassin'S Creed Ultimate Collection 1 & 2 Jc (Win Xpvistawin 7)",
    ],
    metadata: [
      { key: "binding", value: "Video Game" },
      { key: "brand", value: "Encore Software" },
      {
        key: "catalognumberlist",
        value: { CatalogNumberListElement: ["4747836", "8087601"] },
      },
      { key: "ean", value: "0705381267324" },
      { key: "esrbagerating", value: "Mature" },
      {
        key: "feature",
        value: [
          "Sequel to the original Assassin's Creed continues the storyline as you fight to uncover a conspiracy bigger than you could imagine",
          "Utilize an arsenal of weapons",
          "You are an Assassin, a warrior shrouded in secrecy and feared for your ruthlessness.",
        ],
      },
      { key: "format", value: "CD-ROM" },
      { key: "genre", value: "Fighting Action Games" },
      { key: "hardwareplatform", value: "Pc" },
      { key: "label", value: "Encore Software" },
      { key: "manufacturer", value: "Encore Software" },
      { key: "model", value: "26732" },
      { key: "mpn", value: "26732" },
      { key: "numberofitems", value: 1 },
      { key: "operatingsystem", value: "Windows 2000" },
      { key: "packagequantity", value: "1" },
      { key: "partnumber", value: "26732" },
      {
        key: "platform",
        value: ["Windows 7", "Windows Vista", "Windows 2000", "Windows XP"],
      },
      { key: "productgroup", value: "Video Games" },
      { key: "producttypename", value: "SOFTWARE_GAMES" },
      { key: "publisher", value: "Encore Software" },
      { key: "releasedate", value: { $date: "2011-09-01T00:00:00.000+0200" } },
      { key: "studio", value: "Encore Software" },
      { key: "title", value: "Assassin's Creed I & II" },
      { key: "upc", value: "705381267324" },
      { key: "upclist", value: { UPCListElement: ["705381267324"] } },
    ],
    binding: "Video Game",
    brand: "Encore Software",
    catalognumberlist: { CatalogNumberListElement: ["4747836", "8087601"] },
    ean: "0705381267324",
    esrbagerating: "Mature",
    feature: [
      "Sequel to the original Assassin's Creed continues the storyline as you fight to uncover a conspiracy bigger than you could imagine",
      "Utilize an arsenal of weapons",
      "You are an Assassin, a warrior shrouded in secrecy and feared for your ruthlessness.",
    ],
    format: "CD-ROM",
    genre: "Fighting Action Games",
    hardwareplatform: "Pc",
    label: "Encore Software",
    price: 999,
    currency: "USD",
    manufacturer: "Encore Software",
    model: "26732",
    mpn: "26732",
    numberofitems: 1,
    operatingsystem: "Windows 2000",
    packagequantity: "1",
    partnumber: "26732",
    platform: ["Windows 7", "Windows Vista", "Windows 2000", "Windows XP"],
    productgroup: "Video Games",
    producttypename: "SOFTWARE_GAMES",
    publisher: "Encore Software",
    releasedate: { $date: "2011-09-01T00:00:00.000+0200" },
    studio: "Encore Software",
    title: "Assassin's Creed I & II",
    upc: "705381267324",
    upclist: { UPCListElement: ["705381267324"] },
    category: "/games/pc",
    salesrank: 1187,
  },
  {
    _id: { oid: "537f3aaac769230000be8244" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/51HbRcJhurL._SL75_.jpg",
        width: "50",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/51HbRcJhurL._SL160_.jpg",
        width: "107",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/51HbRcJhurL.jpg",
        width: "334",
        height: "500",
      },
    },
    description: [
      "The year is 2108, and the North American Commonwealth is bursting at the seams. For welfare rats like Andrew Grayson, there are only two ways out of the crime-ridden and filthy welfare tenements, where you're restricted to two thousand calories of badly flavored soy every day:<p>You can hope to win the lottery and draw a ticket on a colony ship settling off-world, or you can join the service.<p>With the colony lottery a pipe dream, Andrew chooses to enlist in the armed forces for a shot at real food, a retirement bonus, and maybe a ticket off Earth. But as he starts a career of supposed privilege, he soon learns that the good food and decent health care come at a steep price…and that the settled galaxy holds far greater dangers than military bureaucrats or the gangs that rule the slums.<p>The debut novel from Marko Kloos, <i>Terms of Enlistment</i> is a new addition to the great military sci-fi tradition of Robert Heinlein, Joe Haldeman, and John Scalzi.",
    ],
    metadata: [
      { key: "author", value: "Marko Kloos" },
      { key: "binding", value: "Paperback" },
      { key: "ean", value: "9781477809785" },
      { key: "edition", value: "Revised" },
      { key: "isbn", value: "1477809783" },
      { key: "label", value: "47North" },
      { key: "manufacturer", value: "47North" },
      { key: "numberofitems", value: 1 },
      { key: "numberofpages", value: 346 },
      { key: "productgroup", value: "Book" },
      { key: "producttypename", value: "ABIS_BOOK" },
      {
        key: "publicationdate",
        value: { $date: "2014-01-28T00:00:00.000+0100" },
      },
      { key: "publisher", value: "47North" },
      { key: "releasedate", value: { $date: "2014-01-28T00:00:00.000+0100" } },
      { key: "studio", value: "47North" },
      { key: "title", value: "Terms of Enlistment (Frontlines)" },
    ],
    author: "Marko Kloos",
    binding: "Paperback",
    ean: "9781477809785",
    edition: "Revised",
    isbn: "1477809783",
    label: "47North",
    price: 1495,
    currency: "USD",
    manufacturer: "47North",
    numberofitems: 1,
    numberofpages: 346,
    productgroup: "Book",
    producttypename: "ABIS_BOOK",
    publicationdate: { $date: "2014-01-28T00:00:00.000+0100" },
    publisher: "47North",
    releasedate: { $date: "2014-01-28T00:00:00.000+0100" },
    studio: "47North",
    title: "Terms of Enlistment (Frontlines)",
    category: "/books/scifi",
    salesrank: 7137,
  },
  {
    _id: { oid: "537f3aaac769230000be8245" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/61kucjcR3wL._SL75_.jpg",
        width: "46",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/61kucjcR3wL._SL160_.jpg",
        width: "99",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/61kucjcR3wL.jpg",
        width: "308",
        height: "500",
      },
    },
    description: [
      "Thousands of them have lived underground. They've lived there so long, there are only legends about people living anywhere else. Such a life requires rules. Strict rules. There are things that must not be discussed. Like going outside. Never mention you might like going outside.<br /><br />Or you'll get what you wish for.<br /><br /><br />What the press is saying:<br /><br />Boing Boing's Official Review: \"This story is terrific. I was completely immersed, watching Howey slowly paint a picture of a society gone wrong through the eyes and discovery of some truly compelling characters.\"<br /><br />Wired.com's Official GeekDad Review: \"Howey is among a growing list of authors who are making successful careers of publishing without the assistance of agents and traditional publishing houses. The traditional argument has been that if a book couldn’t find a publisher it probably wasn’t worth reading. However, just as iTunes changed how consumers found music and the way in which bands made their bread, ebook readers, and in particular the Kindle, are changing the ways in which authors find their readers and make a living. All of this means the old assumptions about indie books no longer hold true, and readers need to be prepared to adjust their expectations accordingly. The Wool Omnibus is a great book and deserves recognition as a full fledged contribution to the science fiction genre.\"",
    ],
    metadata: [
      { key: "author", value: "Hugh Howey" },
      { key: "binding", value: "Kindle Edition" },
      { key: "eisbn", value: "9781461057208" },
      { key: "format", value: "Kindle eBook" },
      { key: "isadultproduct", value: "0" },
      { key: "label", value: "Broad Reach" },
      { key: "manufacturer", value: "Broad Reach" },
      { key: "numberofpages", value: 58 },
      { key: "productgroup", value: "eBooks" },
      { key: "producttypename", value: "ABIS_EBOOKS" },
      {
        key: "publicationdate",
        value: { $date: "2011-07-30T00:00:00.000+0200" },
      },
      { key: "publisher", value: "Broad Reach" },
      { key: "releasedate", value: { $date: "2011-07-30T00:00:00.000+0200" } },
      { key: "studio", value: "Broad Reach" },
      { key: "title", value: "Wool - Part One" },
    ],
    author: "Hugh Howey",
    binding: "Kindle Edition",
    eisbn: "9781461057208",
    format: "Kindle eBook",
    isadultproduct: "0",
    label: "Broad Reach",
    manufacturer: "Broad Reach",
    numberofpages: 58,
    productgroup: "eBooks",
    producttypename: "ABIS_EBOOKS",
    publicationdate: { $date: "2011-07-30T00:00:00.000+0200" },
    publisher: "Broad Reach",
    releasedate: { $date: "2011-07-30T00:00:00.000+0200" },
    studio: "Broad Reach",
    title: "Wool - Part One",
    category: "/books/scifi",
    salesrank: 0,
  },
  {
    _id: { oid: "537f3aaac769230000be8246" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/418nqWY-VyL._SL75_.jpg",
        width: "50",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/418nqWY-VyL._SL160_.jpg",
        width: "107",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/418nqWY-VyL.jpg",
        width: "333",
        height: "500",
      },
    },
    description: [
      "If you wish for peace, prepare for war.\r<br />-Royal Navy Motto\r<br />\r<br />Seventy years ago, the interstellar supercarrier Ark Royal was the pride of the Royal Navy.  But now, her weapons are outdated and her solid-state armour nothing more than a burden on her colossal hull.  She floats in permanent orbit near Earth, a dumping ground for the officers and crew the Royal Navy wishes to keep out of the public eye.  \r<br />\r<br />But when a deadly alien threat appears, the modern starships built by humanity are no match for the powerful alien weapons.  Ark Royal and her mismatched crew must go on the offensive, buying time with their lives  And yet, with a drunkard for a Captain, an over-ambitious first officer and a crew composed of reservists and the dregs of the service, do they have even the faintest hope of surviving ...\r<br />\r<br />... And returning to an Earth which may no longer be there?\r<br />\r<br />[Like my other self-published Kindle books, Ark Royal is DRM-free.  You may reformat it as you choose.  There is a large sample of the text – and my other books – on my site: chrishanger.net.  Try before you buy.]\r<br />",
    ],
    metadata: [
      { key: "author", value: "Christopher Nuttall" },
      { key: "binding", value: "Kindle Edition" },
      { key: "format", value: "Kindle eBook" },
      { key: "isadultproduct", value: "0" },
      { key: "numberofpages", value: 443 },
      { key: "productgroup", value: "eBooks" },
      { key: "producttypename", value: "ABIS_EBOOKS" },
      {
        key: "publicationdate",
        value: { $date: "2014-01-14T00:00:00.000+0100" },
      },
      { key: "releasedate", value: { $date: "2014-01-14T00:00:00.000+0100" } },
      { key: "title", value: "Ark Royal" },
    ],
    author: "Christopher Nuttall",
    binding: "Kindle Edition",
    format: "Kindle eBook",
    isadultproduct: "0",
    numberofpages: 443,
    productgroup: "eBooks",
    producttypename: "ABIS_EBOOKS",
    publicationdate: { $date: "2014-01-14T00:00:00.000+0100" },
    releasedate: { $date: "2014-01-14T00:00:00.000+0100" },
    title: "Ark Royal",
    category: "/books/scifi",
    salesrank: 328,
  },
  {
    _id: { oid: "537f3aaac769230000be8168" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/516%2BEoC5amL._SL75_.jpg",
        width: "47",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/516%2BEoC5amL._SL160_.jpg",
        width: "100",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/516%2BEoC5amL.jpg",
        width: "312",
        height: "500",
      },
    },
    description: [
      "Boundless U.S. History is a college-level, introductory textbook that covers the exciting subject of U.S. History. Volume I covers early American history through 1865. Boundless works with subject matter experts to select the best open educational resources available on the web, review the content for quality, and create introductory, college-level textbooks designed to meet the study needs of university students.  ",
    ],
    metadata: [
      { key: "author", value: "Boundless Learning" },
      { key: "binding", value: "Kindle Edition" },
      { key: "eisbn", value: "9781940464183" },
      { key: "format", value: "Kindle eBook" },
      { key: "label", value: "Boundless" },
      { key: "manufacturer", value: "Boundless" },
      { key: "productgroup", value: "eBooks" },
      { key: "producttypename", value: "ABIS_EBOOKS" },
      {
        key: "publicationdate",
        value: { $date: "2013-08-17T00:00:00.000+0200" },
      },
      { key: "publisher", value: "Boundless" },
      { key: "releasedate", value: { $date: "2013-08-28T00:00:00.000+0200" } },
      { key: "studio", value: "Boundless" },
      {
        key: "title",
        value: "Boundless U.S. History, Volume 1: Pre-1492-1865",
      },
    ],
    author: "Boundless Learning",
    binding: "Kindle Edition",
    eisbn: "9781940464183",
    format: "Kindle eBook",
    label: "Boundless",
    manufacturer: "Boundless",
    productgroup: "eBooks",
    producttypename: "ABIS_EBOOKS",
    publicationdate: { $date: "2013-08-17T00:00:00.000+0200" },
    publisher: "Boundless",
    releasedate: { $date: "2013-08-28T00:00:00.000+0200" },
    studio: "Boundless",
    title: "Boundless U.S. History, Volume 1: Pre-1492-1865",
    category: "/books/history",
    salesrank: 0,
  },
  {
    _id: { oid: "537f3aaac769230000be8169" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/61BmQXvZOfL._SL75_.jpg",
        width: "75",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/61BmQXvZOfL._SL160_.jpg",
        width: "160",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/61BmQXvZOfL.jpg",
        width: "500",
        height: "500",
      },
    },
    description: [
      "<p>It's an irresistible combination: Brad Meltzer, a born storyteller, counting down the world's most intriguing unsolved mysteries. And to make this richly illustrated book even richer, each chapter invites the reader along for an interactive experience through the addition of removable facsimile documents—the evidence! It's a treasure trove for conspiracy buffs, a <em>Griffin and Sabine</em> for history lovers.<br /><br />Adapted from <em>Decoded</em>, Meltzer’s hit show on the HISTORY network, <em>History Decoded</em> explores fascinating, unexplained questions. Is Fort Knox empty? Why was Hitler so intent on capturing the Roman “Spear of Destiny”? What’s the government hiding in Area 51? Where did the Confederacy’s $19 million in gold and silver go at the end of the Civil War? And did Lee Harvey Oswald really act alone? Meltzer sifts through the evidence; weighs competing theories;  separates what we know to be true with what’s still—and perhaps forever—unproved or unprovable; and in the end, <em>decodes</em> the mystery, arriving at the most likely solution. Along the way we meet Freemasons, Rosicrucians, Nazi propagandists, and the <em>real</em> DB Cooper.<br /><br />Bound in at the beginning of each story is a custom-designed envelope—a faux 19th-century leather satchel, a U.S. government classified file—containing facsimiles of relevant evidence: John Wilkes Booth’s alleged unsigned will, a map of the Vatican, Kennedy’s death certificate. The whole is a riveting, interactive adventure through the compelling world of mysteries and conspiracies.</p>",
    ],
    metadata: [
      { key: "author", value: ["Brad Meltzer", "Keith Ferrell"] },
      { key: "binding", value: "Hardcover" },
      { key: "brand", value: "Workman Publishing" },
      { key: "color", value: "white" },
      { key: "ean", value: "9780761177456" },
      {
        key: "feature",
        value: [
          "History Decoded Book.",
          "Explores the world's top 10 most fascinating, unexplained conspiracies.",
          "With 30 removable facsimile documents.",
          "Hardcover; 152 pgs.",
        ],
      },
      { key: "isbn", value: "0761177450" },
      { key: "iseligiblefortradein", value: "1" },
      { key: "label", value: "Workman Publishing Company" },
      { key: "manufacturer", value: "Workman Publishing Company" },
      { key: "mpn", value: "17745" },
      { key: "numberofitems", value: 1 },
      { key: "numberofpages", value: 160 },
      { key: "packagequantity", value: "1" },
      { key: "partnumber", value: "17745" },
      { key: "productgroup", value: "Book" },
      { key: "producttypename", value: "ABIS_BOOK" },
      {
        key: "publicationdate",
        value: { $date: "2013-10-22T00:00:00.000+0200" },
      },
      { key: "publisher", value: "Workman Publishing Company" },
      { key: "releasedate", value: { $date: "2013-10-20T00:00:00.000+0200" } },
      { key: "studio", value: "Workman Publishing Company" },
      {
        key: "title",
        value: "History Decoded: The 10 Greatest Conspiracies of All Time",
      },
    ],
    author: ["Brad Meltzer", "Keith Ferrell"],
    binding: "Hardcover",
    brand: "Workman Publishing",
    color: "white",
    ean: "9780761177456",
    feature: [
      "History Decoded Book.",
      "Explores the world's top 10 most fascinating, unexplained conspiracies.",
      "With 30 removable facsimile documents.",
      "Hardcover; 152 pgs.",
    ],
    isbn: "0761177450",
    iseligiblefortradein: "1",
    label: "Workman Publishing Company",
    price: 2495,
    currency: "USD",
    manufacturer: "Workman Publishing Company",
    mpn: "17745",
    numberofitems: 1,
    numberofpages: 160,
    packagequantity: "1",
    partnumber: "17745",
    productgroup: "Book",
    producttypename: "ABIS_BOOK",
    publicationdate: { $date: "2013-10-22T00:00:00.000+0200" },
    publisher: "Workman Publishing Company",
    releasedate: { $date: "2013-10-20T00:00:00.000+0200" },
    studio: "Workman Publishing Company",
    title: "History Decoded: The 10 Greatest Conspiracies of All Time",
    category: "/books/history",
    salesrank: 6006,
  },
  {
    _id: { oid: "537f3aaac769230000be816a" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/51BZh0mp4wL._SL75_.jpg",
        width: "50",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/51BZh0mp4wL._SL160_.jpg",
        width: "107",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/51BZh0mp4wL.jpg",
        width: "333",
        height: "500",
      },
    },
    description: [
      "This book was converted from its physical edition to the digital format by a community of volunteers. You may find it for free on the web. Purchase of the Kindle edition includes wireless delivery.",
    ],
    metadata: [
      { key: "author", value: "Jacob Abbott" },
      { key: "binding", value: "Kindle Edition" },
      { key: "format", value: "Kindle eBook" },
      { key: "isadultproduct", value: "0" },
      { key: "numberofpages", value: 91 },
      { key: "productgroup", value: "eBooks" },
      { key: "producttypename", value: "ABIS_EBOOKS" },
      {
        key: "publicationdate",
        value: { $date: "2012-12-18T00:00:00.000+0100" },
      },
      { key: "releasedate", value: { $date: "2012-12-18T00:00:00.000+0100" } },
      { key: "title", value: "History of Cleopatra, Queen of Egypt" },
    ],
    author: "Jacob Abbott",
    binding: "Kindle Edition",
    format: "Kindle eBook",
    isadultproduct: "0",
    numberofpages: 91,
    productgroup: "eBooks",
    producttypename: "ABIS_EBOOKS",
    publicationdate: { $date: "2012-12-18T00:00:00.000+0100" },
    releasedate: { $date: "2012-12-18T00:00:00.000+0100" },
    title: "History of Cleopatra, Queen of Egypt",
    category: "/books/history",
    salesrank: 0,
  },
  {
    _id: { oid: "537f3aaac769230000be816b" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/51O3ln9pXyL._SL75_.jpg",
        width: "60",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/51O3ln9pXyL._SL160_.jpg",
        width: "128",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/51O3ln9pXyL.jpg",
        width: "400",
        height: "500",
      },
    },
    description: [
      "History of the United States is a work by Charles Austin Beard now brought to you in this new edition of the timeless classic.",
    ],
    metadata: [
      { key: "author", value: "Charles Austin Beard" },
      { key: "binding", value: "Paperback" },
      { key: "ean", value: "9781481934060" },
      { key: "isbn", value: "1481934066" },
      { key: "iseligiblefortradein", value: "1" },
      { key: "label", value: "CreateSpace Independent Publishing Platform" },
      {
        key: "manufacturer",
        value: "CreateSpace Independent Publishing Platform",
      },
      { key: "numberofpages", value: 440 },
      { key: "productgroup", value: "Book" },
      { key: "producttypename", value: "ABIS_BOOK" },
      {
        key: "publicationdate",
        value: { $date: "2013-01-08T00:00:00.000+0100" },
      },
      {
        key: "publisher",
        value: "CreateSpace Independent Publishing Platform",
      },
      { key: "studio", value: "CreateSpace Independent Publishing Platform" },
      { key: "title", value: "History of the United States" },
    ],
    author: "Charles Austin Beard",
    binding: "Paperback",
    ean: "9781481934060",
    isbn: "1481934066",
    iseligiblefortradein: "1",
    label: "CreateSpace Independent Publishing Platform",
    price: 1999,
    currency: "USD",
    manufacturer: "CreateSpace Independent Publishing Platform",
    numberofpages: 440,
    productgroup: "Book",
    producttypename: "ABIS_BOOK",
    publicationdate: { $date: "2013-01-08T00:00:00.000+0100" },
    publisher: "CreateSpace Independent Publishing Platform",
    studio: "CreateSpace Independent Publishing Platform",
    title: "History of the United States",
    category: "/books/history",
    salesrank: 77922,
  },
  {
    _id: { oid: "537f3aaac769230000be816c" },
    images: {
      small: {
        url: "http://ecx.images-amazon.com/images/I/51fws-Hns1L._SL75_.jpg",
        width: "49",
        height: "75",
      },
      medium: {
        url: "http://ecx.images-amazon.com/images/I/51fws-Hns1L._SL160_.jpg",
        width: "105",
        height: "160",
      },
      large: {
        url: "http://ecx.images-amazon.com/images/I/51fws-Hns1L.jpg",
        width: "328",
        height: "500",
      },
    },
    description: [
      "This updated and revised edition of the American Book Award-winner and national bestseller revitalizes the truth of America’s history, explores how myths continue to be perpetrated, and includes a new chapter on 9/11 and the Iraq War.<br><br>Americans have lost touch with their history, and in <i>Lies My Teacher Told Me</i> Professor James Loewen shows why. After surveying eighteen leading high school American history texts, he has concluded that not one does a decent job of making history interesting or memorable. Marred by an embarrassing combination of blind patriotism, mindless optimism, sheer misinformation, and outright lies, these books omit almost all the ambiguity, passion, conflict, and drama from our past.<BR><BR>In this revised edition, packed with updated material, Loewen explores how historical myths continue to be perpetuated in today's climate and adds an eye-opening chapter on the lies surrounding 9/11 and the Iraq War. From the truth about Columbus's historic voyages to an honest evaluation of our national leaders, Loewen revives our history, restoring the vitality and relevance it truly possesses. <BR><BR>Thought provoking, nonpartisan, and often shocking, Loewen unveils the real America in this iconoclastic classic beloved by high school teachers, history buffs, and enlightened citizens across the country.",
    ],
    metadata: [
      { key: "author", value: "James W. Loewen" },
      { key: "binding", value: "Paperback" },
      { key: "brand", value: "Brand: New" },
      { key: "ean", value: "9780743296281" },
      { key: "edition", value: "Revised" },
      { key: "feature", value: "Used Book in Good Condition" },
      { key: "isbn", value: "0743296281" },
      { key: "label", value: "Touchstone" },
      { key: "manufacturer", value: "Touchstone" },
      { key: "numberofitems", value: 1 },
      { key: "numberofpages", value: 464 },
      { key: "productgroup", value: "Book" },
      { key: "producttypename", value: "ABIS_BOOK" },
      {
        key: "publicationdate",
        value: { $date: "2007-10-16T00:00:00.000+0200" },
      },
      { key: "publisher", value: "Touchstone" },
      { key: "releasedate", value: { $date: "2007-10-16T00:00:00.000+0200" } },
      { key: "sku", value: "NEW0000000125" },
      { key: "studio", value: "Touchstone" },
      {
        key: "title",
        value:
          "Lies My Teacher Told Me: Everything Your American History Textbook Got Wrong",
      },
    ],
    author: "James W. Loewen",
    binding: "Paperback",
    brand: "Brand: New",
    ean: "9780743296281",
    edition: "Revised",
    feature: "Used Book in Good Condition",
    isbn: "0743296281",
    label: "Touchstone",
    price: 1799,
    currency: "USD",
    manufacturer: "Touchstone",
    numberofitems: 1,
    numberofpages: 464,
    productgroup: "Book",
    producttypename: "ABIS_BOOK",
    publicationdate: { $date: "2007-10-16T00:00:00.000+0200" },
    publisher: "Touchstone",
    releasedate: { $date: "2007-10-16T00:00:00.000+0200" },
    sku: "NEW0000000125",
    studio: "Touchstone",
    title:
      "Lies My Teacher Told Me: Everything Your American History Textbook Got Wrong",
    category: "/books/history",
    salesrank: 2501,
  },
];
export default data;
